name: Backend CI/CD

on:
  push:
    branches:
      - dev
      - staging
      - master
  pull_request:
    branches:
      - dev
      - staging
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Docker tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
            echo "tag=staging" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == "master" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-api:${{ steps.vars.outputs.tag }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-api:${{ steps.vars.outputs.tag }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-api:${{ steps.vars.outputs.tag }}
            docker stop backend-api || true
            docker rm backend-api || true
            docker run -d --name backend-api -p 4000:4000 ${{ secrets.DOCKER_USERNAME }}/backend-api:${{ steps.vars.outputs.tag }}
