name: Backend CI/CD

on:
  push:
    branches:
      - staging
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Docker image tag
        id: vars
        run: echo "tag=${GITHUB_REF_NAME}-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-api:${{ steps.vars.outputs.tag }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-api:${{ steps.vars.outputs.tag }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
              docker stop backend-api-staging || true
              docker rm backend-api-staging || true
              docker pull ${{ secrets.DOCKER_USERNAME }}/backend-api:${{ steps.vars.outputs.tag }}
              docker run -d --name backend-api-staging -p 3002:3001 ${{ secrets.DOCKER_USERNAME }}/backend-api:${{ steps.vars.outputs.tag }}
            elif [[ "${GITHUB_REF_NAME}" == "master" ]]; then
              docker stop backend-api || true
              docker rm backend-api || true
              docker pull ${{ secrets.DOCKER_USERNAME }}/backend-api:${{ steps.vars.outputs.tag }}
              docker run -d --name backend-api -p 8080:3001 ${{ secrets.DOCKER_USERNAME }}/backend-api:${{ steps.vars.outputs.tag }}
            fi
