name: Backend CI

on:
  push:
    branches:
      - dev
      - staging
  pull_request:
    branches:
      - dev
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend
        run: ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          if [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-api:staging .
          else
            docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-api:dev .
          fi

      - name: Push Docker image
        run: |
          if [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/backend-api:staging
          else
            docker push ${{ secrets.DOCKER_USERNAME }}/backend-api:dev
          fi
