name: Backend CI/CD (Dev)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-api:dev .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-api:dev

      - name: Deploy to EC2 (Dev)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-api:dev
            docker stop backend-api || true
            docker rm backend-api || true
            docker run -d --name backend-api -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/backend-api:dev
